# -*- mode: ruby -*-
# # vi: set ft=ruby :

Vagrant.require_version ">= 2.0.0"
VAGRANTFILE_API_VERSION = "2"
IMAGE_NAME = "ubuntu/bionic64"


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.vm.provider "virtualbox" do |v|
        v.gui = true
        v.memory = 4096
        v.cpus = 2

        v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
        v.customize ["modifyvm", :id, "--graphicscontroller", "vboxvga"]
        v.customize ["modifyvm", :id, "--ioapic", "on"]
        v.customize ["modifyvm", :id, "--vrde", "off"]
        v.customize ["modifyvm", :id, "--accelerate3d", "on"]

        v.customize ["modifyvm", :id, "--rtcuseutc", "on"]
        v.customize ["modifyvm", :id, "--hwvirtex", "on"]
        v.customize ["modifyvm", :id, "--nestedpaging", "on"]
        v.customize ["modifyvm", :id, "--vtxvpid", "on"]
        v.customize ["modifyvm", :id, "--largepages", "on"]
        v.customize ["modifyvm", :id, "--acpi", "on"]
        v.customize ["modifyvm", :id, "--groups", "/JVM Development"]

        # change the network card hardware for better performance
        v.customize ["modifyvm", :id, "--nictype1", "virtio"]
        v.customize ["modifyvm", :id, "--nictype2", "virtio"]

        # suggested fix for slow network performance
        # see https://github.com/mitchellh/vagrant/issues/1807
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

        v.customize ["modifyvm", :id, "--vram", "128"]
    end

    config.vm.define "devmachine" do |devmachine|
        devmachine.vm.box = IMAGE_NAME
        devmachine.vm.hostname = "devm"
        devmachine.vm.boot_timeout = 300
        devmachine.vm.box_check_update = true
        devmachine.vm.graceful_halt_timeout = 60
        devmachine.vm.post_up_message = "Login credentials are vagrant/vagrant"
        devmachine.vm.synced_folder ".", "/vagrant", disabled: false

        devmachine.ssh.password = "vagrant"
        devmachine.ssh.username = "vagrant"        
        devmachine.ssh.insert_key = true
        devmachine.ssh.forward_agent = true        

        devmachine.vm.provision "10_ubuntu.sh", type: :shell, path: "scripts/10_ubuntu.sh", privileged: true

        devmachine.vm.provision "docker" do |d|
            d.pull_images "tomcat"
        end
        
        devmachine.vm.provision :shell, inline: 'reboot'
    end
end
